name: Execução dos teste unitarios com Jest

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout do repositório
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: action/setup-node@v3
              with:
                node-version: 20

            - name: Instalar dependencias
              run: npm install

            - name: Execultar Testes
              run: npm run test